/* THIS IS AN AUTOGENERATED FILE, PLEASE EDIT servicesJLL.py */
#ifndef __SERVICES_H
#define __SERVICES_H
struct service { char name[0x100]; int port; bool should_log; int frequency; int decimation; };
static struct service services[] = {
  { "testJoystick", 8001, true, 0, -1 },
};
#endif

